### ISSUE TITLE
GUI - helping users with tooltip 

### ISSUE THREAD

**Issue by gmat** [MetaSys-LISBP/IsoCor#13]
In addition to the documentation, we will investigate on the GUI if the use of tooltip could help user choosing the good option or finding some values like the purity tracer.

**Comment by gmat** [comment]
where should balloon could be useful in the interface ?

**Comment by gmat** [comment]
publish the branch [*balloongui*](https://github.com/MetaSys-LISBP/IsoCor/commit/29641e3a8d4f801bef93fa2212a43cb607145559) with a useful class Tooltip found on stackoverflow to do this. 

4 context helpers are declaring for the example. See line 700 in isocorgui.py.

This branch is based on the threading branch version.

Couldn't use *Balloon* from *Tix*. Tix is deprecated since version 3.6. 

> This Tk extension is unmaintained and should not be used in new code. Use tkinter.ttk instead.

**Comment by pierremillard** [comment]
implemented in #17
