### ISSUE TITLE
add a update checker feature

### ISSUE THREAD

**Issue by gmat** [MetaSys-LISBP/IsoCor#14]
It could be useful to add at the startup gui a network checker for lasted version of isocor.

Could be done maybe with pip package.

**Comment by gmat** [comment]
finaly feature made with url request to a VERSION file. 
https://github.com/MetaSys-LISBP/IsoCor/commit/b88d10c220bb057101dc5ec4df64ae232088df94

**Comment by pierremillard** [comment]
implemented in #17
