### ISSUE TITLE
Correction matrices and vectors truncated in logs

### ISSUE THREAD

**Issue by pierremillard** [MetaSys-LISBP/IsoCor#18]
Correction matrices and vectors saved in log files (when "verbose logs" is activated) are truncated for metabolites with a large number of tracer atoms. We will update IsoCor to return the full vectors and matrices in all situations.

**Comment by gmat** [comment]
enhancement ? Is it not a bug ? Do you have a input test to share to reproduce this ? I don't clearly understand the concept with large number of tracer atoms.
Thanks

**Comment by pierremillard** [comment]
This is not blocking and results are not impacted, so to me this is not a bug.

The size of correction vectors and matrices depends on the number of atoms of tracer element.

For metabolites with a low number of atoms of tracer element, vectors and matrices are correctly displayed in the log file. However, for metabolites with a large number of atoms of tracer element, matrices are truncated. Here an example file corresponding to 2H labeling experiments on a lipid with 94 H atoms ([test.zip](https://github.com/MetaSys-LISBP/IsoCor/files/3823634/test.zip)  provided by Ondrej Kuda). The log output is:

> 2019-11-06 13:27:29 - isocor.mscorrectors - DEBUG - Done computing correction matrix (convolution) for TAG493: [[5.54930067e-001 5.54993891e-003 5.55057723e-005 ... 5.60832737e-185
>   5.60897240e-187 5.60961750e-189]
>  [3.21653016e-001 5.52660214e-001 1.10223028e-002 ... 5.10838371e-181
>   5.16450000e-183 5.22062913e-185]
>  [9.83697039e-002 3.19393357e-001 5.50389573e-001 ... 2.30121837e-177
>   2.35206179e-179 2.40346668e-181]
>  ...
>  [0.00000000e+000 0.00000000e+000 5.92878775e-323 ... 3.57456066e-001
>   2.66909981e-001 1.15632525e-001]
>  [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 1.65583397e-001
>   3.55547532e-001 2.67813857e-001]
>  [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 4.61112430e-002
>   1.64366690e-001 3.53645595e-001]]

**Comment by pierremillard** [comment]
fix proposed by @gmat 

line 294 in mscorrectors.py

`logger.debug("Done computing correction matrix (convolution) for %s: %s", self.label, correction_matrix.tolist())`

**Comment by pierremillard** [comment]
corrected in #20
