### ISSUE TITLE
Error invalid file 

### ISSUE THREAD

**Issue by bowenli37** [MetaSys-LISBP/IsoCor#4]
On a Ubuntu 16.04 (64bit) OS with python 3.5, isocor was installed with pip. When I run isocor or python3 -m isocor in the terminal, a window popped out "Error: invalid file: PosixPath('/home/user/isocordb/Isotopes.dat')". The Isotopes.dat file is in the right folder and readable.

**Comment by bdelepine** [comment]
Hi @bowenli37, thank you for the bug report!

There was a compatibility issue with Python 3.5 and IsoCor v2.0.4. I just released v2.0.5 which should fix the problem.

Could you update your IsoCor version and reopen the issue if you still experience a problem?

```
pip install --upgrade isocor
```

IsoCor version should be v2.0.5.


Many thanks!
